"""Initial migration.

Revision ID: 3c11e8c1f26d
Revises: 
Create Date: 2024-05-30 09:52:34.290449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c11e8c1f26d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ippis', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inactive_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ippis', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unknown_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ippis', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ippis', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ippis')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('unknown_user')
    op.drop_table('inactive_user')
    op.drop_table('active_user')
    # ### end Alembic commands ###
